### PR TITLE
Updated to FSharp.Compiler.Service 16.0.2

### PR DESCRIPTION
**Pull request by xperiandri**

### CODE REVIEW

**Comment by sageserpent-open** [comment]
Hi Andrii,

Thanks for the pull request, but I don't know what you are trying to achieve here - I can see you have reformatted one of the source files and updated the fsharp compiler dependencies, but I don't see what this is leading to or why.

The changes look fine, but I would like to see a description in the PR.

Also, did you test the plugin after making the changes? I really should have written an automated test suite for this project; however it was just done as a spike to investigate the Semantic Merge plugin API.

Regards,

Gerard

**Comment by sageserpent-open** [comment]
Actually, I can see from the pull request title that this is purely for updating the dependencies, so that answers my first question.

Given that its a spike project without automated tests, I'll break a rule and say that I'd rather take the changes in the spirit of cooperation and worry about possible breakage later.

Of course, you might want to add automated tests yourself on our own fork... :-)

Thanks for the pull request, Andrii.

**Comment by xperiandri** [comment]
I wanted to check if it works with GMaster.
It does not.
I asked them on Twitter about that then.

**Comment by sageserpent-open** [comment]
Fine - I'll revert your commit then.

**Comment by xperiandri** [comment]
Why? It is not because of my commit

**Comment by xperiandri** [comment]
It just does not work in general. Maybe I don't know how to plug it into GMaster or it does not support plugins yet.

**Comment by sageserpent-open** [comment]
I've not heard of GMaster  - this is a spike project for plugging into Plastic SCM / Semantic Merge. Perhaps you thought it was for another purpose? Anyway, I hope it is of some use to you for whatever purpose you have in mind.

All the best,

Gerard

**Pull request merged**
